---
title: "Module 2: Life Insurance Draft"
author: "Jack Conway and Marcus Milazzo"
date: "9/22/2017"
output: pdf_document
---

#Introduction

In the previous section on life tables, we laid the foundation for understanding how probability is involved in modeling human life. Death is indeed a random event, and actuaries in life insurance are tasked with developing systems that reduce its financial impact. This can be done in a variety of ways. In this section we aim to introduce many types of life insurance and how these models are derived using basic principles of probability and finance.

#2.1
To model these different types of insurance, we rely on slight variations of the benefit function, $b_t$, and the discount function, $v_t$, where $v_t$ is the discount factor from the time of the payment to the time of policy issue. We then define *t* as the length of the interval from issue to death. 

If we let $T$ = $T(x)$ be the random variable for the insured’s future lifetime at policy issue, then we can write the present value of the benefit as the random variable, $z_T$, which we will denote $Z$. We now have
\[Z=b_T v_T\].
The expected value of $Z$, is what we call the *actuarial present value* of the insurance.
Since $Z$ is a random variable, we are interested in its probability density, which is clearly dependent on the probability density of $T$.


We’ll begin with insurance that provides payment only if the insured dies within a certain *n*-year term. This is called **$n$-year term life insurance**. To derive a formula for the actuarial present value of *n*-year term life insurance we need to specify $b_t$, $v_t$, and $Z$. Let
\[ b_t =  \left\{
\begin{array}{ll}
      1 & t\le n \\
      0 & t > n, \\
\end{array} 
\right. \]
\[v_t = v^{t} \hspace{.5cm} t\ge 0 ,\]
\[ Z =  \left\{
\begin{array}{ll}
      v^{T} & T\le n \\
      0 & T > n. \\
\end{array} 
\right. \]

The general symbol for the actuarial present value of an insurance paying the unit benefit is A. For the *n*-year term life insurance with a unit payable at the death of (x), $E[Z]$ is denoted Ax:n. We can now use the pdf of $T$ to obtain
\[ \bar{A}_{x:n}^1 = E[Z] = E[z_t] = \int_{o}^{\infty}\ z_t\ f_T (t)\ dt = \int_{0}^{n} v^t\ _{t}p_x\ \mu_x (t)\ dt\ = \int_{0}^{n} e^{-\delta t}\ _{t}p_x\ \mu_x (t)\ dt \]
where the force of interest is assumed to be constant. This assumption remains for the rest of this section.

Now that we have $E[Z]$, a natural next step is finding $Var[Z]$. With a unit amount payable at death, it’s easy to show
\[ E[Z^j] \ @ \ \delta_t = E[Z] \ @ \ j \delta_t \].
This is called the **rule of moments**. So,
\[ Var(Z) = 2Ax:n - (Ax:n)^2 \]
and 2Ax:n is for force of interest $2\delta$

\vspace{1cm}

**Whole life insurance** is simply the limiting case of *n*-year term insurance as $n \rightarrow \infty$. So, a payment is provided following the death of the insured at any point in the future. Now, we have
$$
\begin{aligned}
b_t &=  1 \hspace{.5cm} t\ge0, \\
v_t &= v^t \hspace{.5cm} t\ge0, \\
Z &= v^t \hspace{.5cm} t\ge0. \\
\end{aligned}
$$
and
\[ \bar{A}_{x} = E[Z]= \int_{o}^{\infty}\ z_t\ f_T (t)\ dt = \int_{0}^{\infty} v^t\ _{t}p_x\ \mu_x (t)\ dt \]

\vspace{1cm}

An **$n$-year pure endowment** provides a payment at the end of the *n*th year if the insured survives at least *n* years from the time of the policy issue. Now we let
\[ b_t =  \left\{
\begin{array}{ll}
      0 & t\le n \\
      1 & t > n, \\
\end{array} 
\right. \]
\[v_t = v^{t} \hspace{.5cm} t\ge 0 ,\]
\[ Z =  \left\{
\begin{array}{ll}
      0 & T\le n \\
      v^n & T > n. \\
\end{array} 
\right. \]
Then we add that $Z =v^n \Upsilon$, where $\Upsilon$ is the indicator with the value 1 if if the insured survives to $(x+n)$. With this endowment, the size and time of the payment is predetermined so the only uncertainty in this problem is whether or not the payment occurs. Noting that $\Upsilon$ is a Bernoulli random variable, it’s clear that
\[ Ax:n = E[Z] = v^n \ E[\Upsilon] = v^n \ _{n}p_x ,\]
and
\[Var(Z) = v^{2n}Var(\Upsilon) = v^{2n}\ _{n}p_x \ _{n}q_x .\]

\vspace{1cm}

Combining what we know about endowments and insurance, we move on to **$n$-year endowment insurance**. Like the name suggests, this provides payment either after the death of the insured, or if the insured survives the $n$-year term. Again, we modify our core functions to align with the new definition:
\[ b_t = \left\{
\begin{array}{ll}
     1 & t\ge 0,
\end{array}
\right. \]
\[v_t = \left\{
\begin{array}{ll}
     v^{t} & t\le n \\
     v^{n} & t>n, \\
\end{array}
\right. \]
\[ Z =  \left\{
\begin{array}{ll}
      0 & T\le n \\
      v^n & T > n. \\
\end{array} 
\right. \]

Since $b_t  = 1$, we use the fact that 
\[ E[Z^j] \ @ \ \delta_t = E[Z] \ @ \ j \delta_t \]
and
\[ Var(Z) = 2Ax:n - (Ax:n)^2 .\]

\vspace{1cm}

An **$m$-year deferred insurance** provides a benefit only if the insured dies at least $m$ years after policy issue. With a unit amount payable at the moment of death,
\[ b_t =  \left\{
\begin{array}{ll}
      1 & t > m \\
      0 & t \le m, \\
\end{array} 
\right. \]
\[v_t = v^{t} \hspace{.5cm} t > 0 ,\]
\[ Z =  \left\{
\begin{array}{ll}
      v^{T} & T > m \\
      0 & T \le m. \\
\end{array} 
\right. \]

The actuarial present value is
\[ m|Ax =  \int_{m}^{\infty} v^t\ _{t}p_x\ \mu_x (t)\ dt. \]


\vspace{1cm}

The last type of insurance we will introduce is **annually increasing whole life insurance**. This insurance provides 1 at the moment of death during the first year, 2 at the moment of death in the second year, and so on. Our functions become
\[ b_t = \left \lfloor{t+1}\right \rfloor \hspace{.5cm} t \ge 0, \]
\[ v_t = v^t \hspace{.5cm} t \ge 0, \]
\[ Z =  \left \lfloor{T+1}\right \rfloor v^T \hspace{.5cm} T \ge 0. \]

The actuarial present value is
\[ (I\bar{A})_x = E[Z] = \int_{0}^{\infty} \left \lfloor{t+1}\right \rfloor \ v^t\ _{t}p_x\ \mu_x (t)\ dt. \]

Since $b_t$ is no longer just 0 or 1, we can’t find the higher moments by using the actuarial present value at an adjusted force of interest like we did in previous examples. The moments must be calculated directly from their definitions.


\vspace{1cm}

As you can imagine, there are even more types of insurance that can be created by varying our functions slightly. For example, *m*-thly increasing whole life insurance*, continuously increasing whole life insurance, *m*-thly increasing n-year term life insurance, and annually decreasing *n*-year term life insurance. Also recall that we’ve been using the assumption that insurance payments happen at the moment of death; but it’s common to have insurance payments at other times such as the end of the death year.

We hope by now that it’s clear that the actuarial present value and variance of these can be found with slight manipulations to our formulas, and a little bit of work. Over time, one can memorize the details of each type of insurance and endowment, but there is value in understanding where the formulas come from and to be able to recreate them if needed. For reference, summary tables have been provided in the appendix that include the insurances covered in this section and more.

\newpage 

#Problems

##1.
The pdf of future lifetime, T, for (x) is assumed to be
\[ f_{t}(t) =  \left\{
\begin{array}{ll}
      1/60 & 0 \le t \le 60 \\
      0 & \text{elsewhere}. \\
\end{array} 
\right. \]

a. Calculate the actuarial present value at a force of interest $\delta$ for a whole life insurance of a unit amount issued to (x).
b. Calculate the variance.

##2.
Now, assume we are interested in 10 independent individuals. Each ($x$) is insured for 5 units payable at the moment of death.

a. Write the functions $b_t$, $v_t$, and Z for an individual.

b. Calculate the actuarial present value and variance for the group of individuals with constant force of mortality, $\mu$ = .02, and assume the funds are to be withdrawn from a fund earning $\delta$ = .04. (Hint: Find the APV for a single individual first.)

c. Calculate the minimum amount at $t$ = 0 so that the probability is approximately .99 that there are sufficient funds to pay the benefits for the group. (Hint: Use a normal approximation.)

##3. 
Example where they need to write the functions for one of the types of insurance that I didn’t cover. Find E[Z] and Var(Z). Maybe more?
##4
Example using lifecontingencies functions for APV

\newpage

#Solutions
##1.
a. Since this is whole life insurance,
\[ \bar{A}_{x} = E[Z]= \int_{o}^{\infty}\ z_t\ f_T (t)\ dt = \int_{0}^{60} e^{-\delta t} \frac{1}{60}\ dt = frac{1-e^-60\delta}{60\delta}.\]


b.  Using the rule of moments,
\[Var(Z) = E[Z^2] - (E[Z])^2 = \frac{1-e^{-60(2\delta)}}{60(2\delta)} - \left(\frac{1-e^{-60\delta}}{60\delta}\right)^2 \]


##2.
a. $$
\begin{aligned}
b_t &=  5 \hspace{.5cm} t\ge0, \\
v_t &= v^t \hspace{.5cm} t\ge0, \\
Z &= 5v^t \hspace{.5cm} T\ge0. \\
\end{aligned}
$$

b. 

c. 

