---
title: "Module 2: Life Insurance Draft"
author: "Jack Conway and Marcus Milazzo"
date: "9/22/2017"
header-includes:
   - \usepackage{actuarialangle}
output: pdf_document
---


#Introduction

Life insurance is a contract between an insurance company and a policy holder where the insurer agrees to pay a sum of money in exchange for a premium paid by the insured. The purpose of life insurance is to mitigate the financial impact that results from the premature death of the insured. Death is indeed a random event, and actuaries in life insurance are tasked with developing systems that account for the probability of death and the payments to be made. This can be done in a variety of ways. In this section we aim to introduce the main types of life insurance and how these models are derived using basic principles of probability and finance. By the end of this module, the reader should have an understanding of the basics of life insurance, and some insight on how actuaries deal with these problems in real life.

#2.1 Basic Insurance Computations

A major component of life insurance is the amount that the insurer pays, which we call the benefit. The benefit can of course be any positive value, but for our introduction we will only consider benefits of 0 or 1. Recall that the curtate future lifetime, *k*, is the number of future years completed by (*x*) prior to death. We base our models around the curtate future lifetime because we are concerned with insurances payable at the end of the year of death. We rely on slight variations of the benefit function, $b_{k+1}$, and the discount function, $v_{k+1}$, where $v_{k+1}$ is the discount factor from the time of the payment to the time of policy issue. 

Now we will write the present value of the benefit as the random variable, $z_{k+1}$, which we will denote $Z$. We now have
\[Z=b_{k+1}\ v_{k+1}\].

The expected value of $Z$, is what we call the **actuarial present value** (APV) of the insurance. The actuarial present value takes the time value of money concept, and adjusts it for the probability of payment at a given time. To get a better feel for actuarial present value, we’ll compute it for a simple case.

Suppose a person is going to die at some point during the next four years, and there is a policy that pays 1 at the end of each year *only if* the insured dies during that year (i.e. $b_T$ = 1 or 0 depending on death). With a discount rate of .08 and a .25 probability of payment each year, we have
\[ 
\text{E}[Z] = \text{APV} = (1)(.25)(v^1) + (1)(.25)(v^2) + (1)(.25)(v^3) + (1)(.25)(v^4) \approx 0.828.
\]

So, the insurer expects to pay a benefit of .828. What happens if the insured has a much higher chance of dying during the first of the next four years? For example,
\[ 
\text{E}[Z] = \text{APV} = (1)(.97)(v^1) + (1)(.01)(v^2) + (1)(.01)(v^3) + (1)(.01)(v^4) \approx 0.922.
\]
Or in the opposite extreme case,
\[ 
\text{E}[Z] = \text{APV} = (1)(.01)(v^1) + (1)(.01)(v^2) + (1)(.01)(v^3) + (1)(.97)(v^4) \approx 0.739.
\]

In the unit payment case, the actuarial present value behaves as we expect it to from time value of money principles, with the probabilities acting as “payments.” The reader may have noticed something about the nature of the probabilities that we were using in the examples above. They are exactly the probability concepts that we introduced in the life tables modules. For example, in the example directly above, the first probability of payment, .01, is the probability that a life dies in the first year. The second .01 is the probability that a life survives the first year, and then dies during the second year. The last probability, .97, is the probability that the life survives the first three years, and dies the fourth year.

Remembering the notation from the last module, we can write the general formula for our above examples as
\[
A^{1}_{x:\angl{n}} = \text{E}[Z] = \sum_{k=0}^{n-1} v^{k+1} \ _{k}p_{x} \ q_{x+k}
\]



#2.2 More On How Insurance Works

Now that we have a basic idea of the computations involved for insurance on a single life, we can look at a larger example and its implications. Imagine we are working for a life insurance company, where 10,000 people of age 50 buy a one year term insurance policy with a benefit of $55,000. Each of the insured pays an annual premium of $500 at the beginning of the term so the insurance company collects (10,000)($500) = $5,000,000. The life tables for this group tell us that we can expect 75 people to die in the next year, so we expect to pay out total benefits of ($55,0000)(75) = $4,125,000 one year from now. Discounting at a rate of .08 gives an actuarial present value of approximately $3.8 million. 

In this example, it’s clear the actuaries have a lot to take into account when deciding how to price the insurance. The type of policyholders, length of term, benefit amount, survivorship, and discount rates are all important factors to track and predict when trying to make an accurate model. These problems quickly become more difficult as we add more detail and variation in the important factors, but the concepts remain the same. In the following section, we will introduce a few of the main types of insurance and the mathematical detail behind them.



#2.3 Types of Life insurance

Recall the model we wrote at the end of Section 2.1 that pays a benefit if the insured (*x*) dies within *n* years,
\[
A^{1}_{x:\angl{n}} = \text{E}[Z] = \sum_{k=0}^{n-1} \ v^{k+1} \ _{k}p_{x} \ q_{x+k}
\]
This is the model for **n-year term life insurance**. Here we have defined $b_t$, $v_t$, and $Z$ to be
\[ b_{k+1} =  \left\{
\begin{array}{ll}
     1  &K = 0, 1, ..., n-1 \\ 
      0  &\text{elsewhere}, \\
\end{array} 
\right. \]
\[v_{k+1} = v^{k+1} ,\]
\[ Z =  \left\{
\begin{array}{ll}
      v^{K+1} &K = 0, 1, ..., n-1 \\
      0 &\text{elsewhere}. \\
\end{array} 
\right. \]

Another type of insurance pays a benefit regardless of the time it takes for the death of (*x*), called **whole-life insurance**. We make a slight adjustment to the APV formula written above and let $n \rightarrow \infty$, giving
\[
A_{x} = \text{E}[Z] = \sum_{k=0}^{\infty} \ v^{k+1} \ _{k}p_{x} \ q_{x+k}
\]
Our definitions of $b_t$, $v_t$, and $Z$ from the previous example don’t change except for now the curtate future lifetime can be any nonnegative integer.

An **n-year endowment insurance** pays a benefit if the insured dies within *n* years, and also pays if the insured survives at least *n* years. This gives the functions
\[b_{k+1} = 1 , \hspace{.5cm} k = 0, 1, … ,\]
\[v_{k+1} =  \left\{
\begin{array}{ll}
     v^{k+1}  &k = 0, 1, ..., n-1 \\ 
     v^{n}  &k = n, n+1, ..., \\
\end{array} 
\right. \]
\[ Z =  \left\{
\begin{array}{ll}
      v^{K+1} &K = 0, 1, ..., n-1 \\
      v^{n} &k = n, n+1, ..., \\
\end{array} 
\right. \]

The last concept we will introduce before the exercises is the concept of insurance in the continuous context, with a benefit payable at the moment of death. Moving from discrete insurance to continuous insurance is exactly what you would expect from probability theory --- sums become integrals, and probability functions become probability density functions. We also move away from curtate future lifetime, and return to the idea of $T$, the random variable representing future lifetime. This makes our present value function
\[
z_{t} = b_{t} v_{t}
\]

*Insert n-year term continuous stuff here*


\vspace{1cm}

As you can imagine, there are even more types of insurance that can be created by varying our functions slightly. For example, *m*-thly increasing whole life insurance*, continuously increasing whole life insurance, *m*-thly increasing n-year term life insurance, and annually decreasing *n*-year term life insurance. 

We hope by now that it’s clear that the actuarial present value and variance of these can be found with slight manipulations to our formulas, and a little bit of work. Over time, one can memorize the details of each type of insurance and endowment, but there is value in understanding where the formulas come from and to be able to recreate them if needed. For reference, summary tables have been provided in the appendix that include the insurances covered in this section and more.

\newpage 

#Problems

##1.
The pdf of future lifetime, T, for (x) is assumed to be
\[ f_{t}(t) =  \left\{
\begin{array}{ll}
      1/60 & 0 \le t \le 60 \\
      0 & \text{elsewhere}. \\
\end{array} 
\right. \]

a. Calculate the actuarial present value at a force of interest $\delta$ for a whole life insurance of a unit amount issued to (x).
b. Calculate the variance.

##2.
Now, assume we are interested in 10 independent individuals. Each ($x$) is insured for 5 units payable at the moment of death.

a. Write the functions $b_t$, $v_t$, and Z for an individual.

b. Calculate the actuarial present value and variance for the group of individuals with constant force of mortality, $\mu$ = .02, and assume the funds are to be withdrawn from a fund earning $\delta$ = .04. (Hint: Find the APV for a single individual first.)

c. Calculate the minimum amount at $t$ = 0 so that the probability is approximately .99 that there are sufficient funds to pay the benefits for the group. (Hint: Use a normal approximation.)

##3. 
Example where they need to write the functions for one of the types of insurance that I didn’t cover. Find E[Z] and Var(Z). Maybe more?
##4
Example using lifecontingencies functions for APV

\newpage

#Solutions
##1.
a. Since this is whole life insurance,
\[ \bar{A}_{x} = E[Z]= \int_{o}^{\infty}\ z_t\ f_T (t)\ dt = \int_{0}^{60} e^{-\delta t} \frac{1}{60}\ dt = frac{1-e^-60\delta}{60\delta}.\]


b.  Using the rule of moments,
\[Var(Z) = E[Z^2] - (E[Z])^2 = \frac{1-e^{-60(2\delta)}}{60(2\delta)} - \left(\frac{1-e^{-60\delta}}{60\delta}\right)^2 \]


##2.
a. $$
\begin{aligned}
b_t &=  5 \hspace{.5cm} t\ge0, \\
v_t &= v^t \hspace{.5cm} t\ge0, \\
Z &= 5v^t \hspace{.5cm} T\ge0. \\
\end{aligned}
$$

b. 

c. 


