---
title: "Option Greeks"
author: "Jack Conway and Marcus Milazzo"
date: "9/21/2017"
output: 
    pdf_document: 
        fig_caption: false
---

## 1. Greeks

\qquad The use of the Black-Scholes pricing model to value the call option C and put option P in the previous module relied on 6 different inputs. Looking at the effects of changing the values of those inputs on the value of the call and put option prices P and C is done by differentiating C or P with respect to each variable. These partial derivatives in the Black-Scholes pricing model with respect to each of the 6 different inputs are known as the six **Greeks**.  
\qquad The definition of the six greeks are  

**Delta** ($\Delta$) - The increase in the option price per the increase in stock price.  

**Gamma** ($\Gamma$) - The increase in $\Delta$ per increase in stock price.  

**Vega** - The increase in the option price per precentage pint increase in volatility.  

**Theta** ($\Theta$) - The increase in the option price for an option with a fixed expiry date per time elapsed.  

**Rho** ($\rho$) - The increase in the option price per increase in the continuously compounded risk-free return r.  

**Psi** ($\Psi$) - The increase in the option price per increase in the continuous dividend yield.  


## 1.1 Delta  

## 1.2 Gamma  

## 1.3 Vega  
 
## 1.4 Theta  

## 1.5 Rho  

## 1.6 Psi  

\newpage

## Problems

\newpage

## Solutions  
